export const doerSuyoStyles = {
  doerMainWrapper: {
    flex: 1,
    backgroundColor: '#FAFCFA',
  },
  doerListContainer: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
  },
  doerInfoCallout: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E8F5EE',
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#CDE5D7',
  },
  doerInfoCalloutText: {
    fontSize: 11.5,
    color: '#163523',
    fontWeight: '600',
    flex: 1,
    lineHeight: 16,
  },
  doerAcceptedCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1.2,
    borderColor: '#D7E9DE',
    shadowColor: '#163523',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  doerCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  doerCategoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EAF4EF',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
  },
  doerCategoryChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1E4D2B',
  },
  doerRewardBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#86EFAC',
  },
  doerRewardText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#15803D',
  },
  doerCardTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#163523',
    lineHeight: 20,
    marginBottom: 8,
  },
  doerRequesterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  doerRequesterText: {
    fontSize: 12,
    color: '#52695C',
    flex: 1,
  },
  doerCallMiniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  doerCallMiniBtnText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#059669',
  },
  doerLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  doerLocationText: {
    fontSize: 11.5,
    color: '#658172',
    fontWeight: '500',
    maxWidth: '55%',
  },
  doerDot: {
    fontSize: 11,
    color: '#94A3B8',
  },
  doerDeadlineText: {
    fontSize: 11.5,
    color: '#D97706',
    fontWeight: '700',
  },
  doerCardActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EEF5F1',
  },
  doerContinueBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#1E4D2B',
    borderRadius: 11,
    paddingVertical: 10,
  },
  doerContinueBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  doerCancelBtn: {
    flex: 1.2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: '#FEE2E2',
    borderRadius: 11,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  doerCancelBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#DC2626',
  },
  doerCompletedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2ECE6',
  },
  doerCompletedLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 10,
    paddingRight: 8,
  },
  doerCompletedIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doerCompletedTextCol: {
    flex: 1,
  },
  doerCompletedTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#163523',
    marginBottom: 2,
  },
  doerCompletedRequester: {
    fontSize: 11,
    fontWeight: '600',
    color: '#52695C',
    marginBottom: 2,
  },
  doerCompletedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  doerCompletedDate: {
    fontSize: 10.5,
    color: '#8CA395',
  },
  doerCompletedLocation: {
    fontSize: 10.5,
    color: '#8CA395',
    flex: 1,
  },
  doerCompletedRight: {
    alignItems: 'flex-end',
    gap: 3,
  },
  doerCompletedEarned: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#059669',
  },
  doerCompletedRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  doerCompletedRatingText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#B45309',
  },
  doerCancelledCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 13,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  doerCancelledTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  doerCancelledTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#475569',
    flex: 1,
    paddingRight: 8,
  },
  doerCancelledBadge: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  doerCancelledBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#DC2626',
  },
  doerCancelledSub: {
    fontSize: 11,
    color: '#64748B',
    marginBottom: 6,
  },
  doerCancelledNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F8FAFC',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  doerCancelledNoticeText: {
    fontSize: 10.5,
    color: '#64748B',
    fontStyle: 'italic',
  },
  doerEmptyCard: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#E2ECE6',
    marginTop: 8,
  },
  doerEmptyIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F0F7F3',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  doerEmptyTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 6,
  },
  doerEmptySub: {
    fontSize: 12,
    color: '#658172',
    textAlign: 'center',
    lineHeight: 17,
    marginBottom: 16,
  },
  doerBrowseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1E4D2B',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  doerBrowseBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
