export const doerProfileStyles = {
  doerProfileModalCard: {
    width: '100%',
    maxWidth: 370,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    elevation: 10,
  },
  doerProfileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  doerProfileHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#163523',
  },
  doerProfileHero: {
    alignItems: 'center',
    marginBottom: 14,
  },
  doerProfileAvatarCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#1E4D2B',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    position: 'relative',
  },
  doerProfileAvatarInitials: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  doerVerifiedBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#059669',
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doerProfileName: {
    fontSize: 17,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 3,
  },
  doerVerifiedTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginBottom: 5,
  },
  doerVerifiedTagText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#15803D',
  },
  doerProfileRating: {
    fontSize: 12,
    fontWeight: '600',
    color: '#658172',
  },
  doerStatsGrid: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  doerStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  doerStatValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#163523',
  },
  doerStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 2,
  },
  doerInfoList: {
    gap: 8,
    marginBottom: 12,
  },
  doerInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  doerInfoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    width: 75,
  },
  doerInfoValue: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#163523',
    flex: 1,
  },
  doerBioText: {
    fontSize: 11.5,
    color: '#52695C',
    fontStyle: 'italic',
    lineHeight: 16,
    backgroundColor: '#F3FAF5',
    padding: 10,
    borderRadius: 10,
    marginBottom: 16,
  },
  doerProfileActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  doerProfileCallBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 11,
    gap: 6,
  },
  doerProfileCallBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  doerProfileMsgBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5EE',
    borderRadius: 12,
    paddingVertical: 11,
    gap: 6,
  },
  doerProfileMsgBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#163523',
  },
};
