import { Dimensions } from 'react-native';
import { SCREEN_WIDTH } from '../utils/dashboardLayout';

export const doerDetailsStyles = {
  doerDetailModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    width: Math.min(SCREEN_WIDTH * 0.92, 440),
    maxHeight: Dimensions.get('window').height * 0.78,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
  },
  doerDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF3EE',
    marginBottom: 12,
  },
  doerDetailHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  doerDetailCategoryCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E8F5EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doerDetailCategoryText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#163523',
  },
  doerDetailDateText: {
    fontSize: 11,
    color: '#718C7D',
    fontWeight: '500',
  },
  doerDetailCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doerDetailTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#163523',
    lineHeight: 22,
    marginBottom: 10,
  },
  doerDetailSummaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0FDF4',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#DCFCE7',
    marginBottom: 12,
  },
  doerDetailStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  doerDetailStatusBadgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  doerDetailPayoutBox: {
    alignItems: 'flex-end',
  },
  doerDetailPayoutLabel: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#166534',
    letterSpacing: 0.5,
  },
  doerDetailPayoutValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#15803D',
  },
  doerRequesterCard: {
    backgroundColor: '#F7FCF9',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#CDE5D6',
    marginBottom: 12,
  },
  doerRequesterCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  doerRequesterSectionLabel: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#607B6C',
    letterSpacing: 0.6,
  },
  doerRequesterViewProfilePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 8,
    gap: 2,
  },
  doerRequesterViewProfileText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#059669',
  },
  doerRequesterCardMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  doerRequesterAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#1E4D2B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doerRequesterAvatarText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  doerRequesterName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#163523',
  },
  doerRequesterSubMeta: {
    fontSize: 11,
    color: '#059669',
    fontWeight: '600',
    marginTop: 1,
  },
  doerRequesterCallPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#059669',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    gap: 4,
  },
  doerRequesterCallPillText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  doerInfoGridRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  doerInfoGridTile: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  doerInfoGridTileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  doerInfoIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doerInfoGridLabel: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 0.5,
  },
  doerInfoGridValue: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#1E293B',
    lineHeight: 16,
  },
  doerTaskDescCard: {
    backgroundColor: '#F8FAF8',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E6EEE8',
    marginBottom: 10,
  },
  doerSectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  doerSectionHeaderText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#425C4D',
    letterSpacing: 0.5,
  },
  doerTaskDescBody: {
    fontSize: 12.5,
    color: '#27382F',
    lineHeight: 18,
  },
  doerNotesCard: {
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
    marginBottom: 10,
  },
  doerNotesBody: {
    fontSize: 12.5,
    color: '#78350F',
    lineHeight: 18,
  },
  doerAttachmentsCard: {
    backgroundColor: '#F8FAF8',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E6EEE8',
    marginBottom: 10,
  },
  doerModalInfoHint: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    padding: 10,
    borderRadius: 10,
    gap: 8,
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  doerModalInfoHintText: {
    flex: 1,
    fontSize: 11,
    color: '#166534',
    lineHeight: 15,
  },
  doerTapDetailsHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FAF3',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 4,
    gap: 6,
  },
  doerTapDetailsHintText: {
    flex: 1,
    fontSize: 11,
    fontWeight: '600',
    color: '#059669',
  },
};
