export const editSuyoStyles = {
  editSuyoModalCard: {
    width: '100%',
    maxWidth: 390,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    elevation: 10,
  },
  editSuyoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  editSuyoHeaderTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#163523',
  },
  editSuyoInputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 5,
    marginTop: 8,
  },
  editSuyoTextInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 13.5,
    color: '#163523',
    marginBottom: 4,
  },
  editSuyoRewardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editSuyoQuickAddPill: {
    backgroundColor: '#E8F5EE',
    borderWidth: 1,
    borderColor: '#A7D9B8',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  editSuyoQuickAddText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1E4D2B',
  },
  editSuyoTextArea: {
    minHeight: 65,
    textAlignVertical: 'top',
    paddingTop: 8,
  },
  editSuyoActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EEF4F0',
  },
  editSuyoCancelBtn: {
    flex: 1,
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  editSuyoCancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
  },
  editSuyoSaveBtn: {
    flex: 1.6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
  },
  editSuyoSaveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
