export const favoritesStyles = {
  favoritesModalCard: {
    width: '100%',
    maxWidth: 370,
    height: '70%',
    maxHeight: '82%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    elevation: 10,
  },
  favoritesModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  favSubHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  favSubHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  favFadingEditText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(22, 53, 35, 0.45)',
    textDecorationLine: 'underline',
    textDecorationColor: 'rgba(22, 53, 35, 0.25)',
  },
  favSelectAllText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#DC2626',
  },
  favModalToast: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 7,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  favModalToastText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#B91C1C',
  },
  favoritesTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  favoritesModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#163523',
    letterSpacing: -0.3,
  },
  favoritesCountPill: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 8,
  },
  favoritesCountText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#DC2626',
  },
  favoritesModalSub: {
    fontSize: 11.5,
    color: '#658172',
    marginBottom: 10,
  },
  favoritesScrollList: {
    flex: 1,
    marginTop: 2,
    marginBottom: 6,
  },
  favCardItem: {
    backgroundColor: '#F9FBF9',
    borderRadius: 11,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2ECE6',
    marginBottom: 8,
  },
  favCardItemSelected: {
    borderColor: '#F87171',
    backgroundColor: '#FFF9F9',
  },
  favSelectionCircle: {
    width: 17,
    height: 17,
    borderRadius: 8.5,
    borderWidth: 1.5,
    borderColor: '#B0C7B9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    marginTop: 1,
  },
  favSelectionCircleSelected: {
    backgroundColor: '#DC2626',
    borderColor: '#DC2626',
  },
  favCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  favCardTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#163523',
    lineHeight: 16.5,
    marginBottom: 2.5,
  },
  favCardLocation: {
    fontSize: 10.5,
    color: '#62806E',
    fontWeight: '500',
  },
  favCardReward: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#1E4D2B',
  },
  favDeleteActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  favCancelBottomBtn: {
    flex: 1,
    backgroundColor: '#F0F5F2',
    borderRadius: 10,
    paddingVertical: 9.5,
    alignItems: 'center',
  },
  favCancelBottomBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#52695C',
  },
  favConfirmDeleteBtn: {
    flex: 2,
    backgroundColor: '#DC2626',
    borderRadius: 10,
    paddingVertical: 9.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  favConfirmDeleteBtnDisabled: {
    backgroundColor: '#E5ECE8',
  },
  favConfirmDeleteBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  favConfirmDeleteBtnTextDisabled: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8CA395',
  },
  favCardBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#ECF4EF',
  },
  favCardRequestorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  favAvatarCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#EBF4EE',
    borderWidth: 1,
    borderColor: '#B5D4C2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  favAvatarInitials: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#163523',
  },
  favCardRequestorName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#344E41',
  },
  favTagPill: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  favTagUrgent: {
    backgroundColor: '#FEE2E2',
  },
  favTagToday: {
    backgroundColor: '#FEF3C7',
  },
  favTagNormal: {
    backgroundColor: '#E8F5EE',
  },
  favTagTomorrow: {
    backgroundColor: '#E0F2FE',
  },
  favTagPillText: {
    fontSize: 9.5,
    fontWeight: '700',
  },
  favTagUrgentText: {
    color: '#DC2626',
  },
  favTagTodayText: {
    color: '#D97706',
  },
  favTagNormalText: {
    color: '#1E4D2B',
  },
  favTagTomorrowText: {
    color: '#0369A1',
  },
  favEmptyBox: {
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 6,
  },
  favEmptyTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#163523',
  },
  favEmptySub: {
    fontSize: 11.5,
    color: '#718C7D',
    textAlign: 'center',
    lineHeight: 16,
  },
  favCloseBottomBtn: {
    backgroundColor: '#1E4D2B',
    borderRadius: 10,
    paddingVertical: 9.5,
    alignItems: 'center',
    marginTop: 8,
  },
  favCloseBottomBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
