export const filtersStyles = {
  filterModalCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 22,
    elevation: 10,
  },
  filterSectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#163523',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 14,
    marginBottom: 8,
  },
  filterPillsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterPill: {
    backgroundColor: '#F4F9F6',
    borderWidth: 1,
    borderColor: '#DFECE5',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  filterPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#52695C',
  },
  filterPillGradient: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1.2,
  },
  distanceStepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F4F9F6',
    borderWidth: 1,
    borderColor: '#DFECE5',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    height: 42,
    width: 250,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  distanceStepperArrowBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D4E5DC',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 1,
  },
  distanceStepperArrowBtnDisabled: {
    backgroundColor: '#EEF5F1',
    borderColor: '#E2ECE6',
    elevation: 0,
  },
  distanceStepperDisplay: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  distanceStepperValueText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#163523',
    lineHeight: 17,
  },
  distanceStepperSubText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#658172',
    lineHeight: 13,
  },
  filterModalButtonsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#EEF4F0',
  },
  filterResetButton: {
    flex: 1,
    backgroundColor: '#F0F5F2',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  filterResetButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#52695C',
  },
  filterApplyButton: {
    flex: 1.5,
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  filterApplyButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
