import { Platform } from 'react-native';

export const homeStyles = {
  headerHeroSection: {
    width: '100%',
    height: 185,
    backgroundColor: '#163925',
    overflow: 'hidden',
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  heroTextBlock: {
    flex: 1.1,
    justifyContent: 'center',
    zIndex: 2,
    paddingRight: 8,
  },
  heroImageSticker: {
    width: '58%',
    height: '135%',
    position: 'absolute',
    right: -12,
    top: -15,
    zIndex: 1,
  },
  locationPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    gap: 4,
    marginBottom: 8,
  },
  locationPillText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#D4E8DC',
    letterSpacing: 0.2,
  },
  welcomeSubText: {
    fontSize: 11.5,
    color: '#A8D5B8',
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 2,
  },
  welcomeNameText: {
    fontSize: 21,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
    marginBottom: 4,
    lineHeight: 26,
  },
  welcomeTagline: {
    fontSize: 12,
    color: '#D0EDD9',
    fontWeight: '500',
  },
  whiteContentBody: {
    backgroundColor: '#F8FAF9',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -20,
    paddingHorizontal: 20,
    paddingTop: 12,
    zIndex: 3,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
    marginTop: 8,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#D8E5DF',
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 48,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#163523',
    paddingVertical: Platform.OS === 'ios' ? 8 : 4,
    paddingHorizontal: 0,
    minWidth: 0,
  },
  filterIconButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#D8E5DF',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    elevation: 2,
  },
  filterIconButtonActive: {
    backgroundColor: '#1E4D2B',
    borderColor: '#1E4D2B',
  },
  filterActiveBadgeDot: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#E05A47',
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  filterActiveBadgeText: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontWeight: '800',
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 14,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 14,
  },
  nearestHeaderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF4EF',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 4,
  },
  nearestHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E4D2B',
  },
  availableCountBadge: {
    backgroundColor: '#EAF4EF',
    paddingHorizontal: 8,
    paddingVertical: 2.5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1E5D9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  availableCountBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1E4D2B',
  },
  clearFiltersPill: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 10,
    paddingVertical: 4.5,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  clearFiltersText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  tasksList: {
    gap: 10,
  },
  suyoCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#DFECE5',
    borderRadius: 16,
    padding: 14,
    elevation: 1.5,
  },
  suyoCardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  suyoCardTitle: {
    flex: 1,
    fontSize: 14.5,
    fontWeight: '700',
    color: '#163523',
    marginRight: 10,
    lineHeight: 19,
  },
  suyoCardReward: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E4D2B',
  },
  suyoCardBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  suyoCardDistanceSub: {
    fontSize: 12,
    color: '#718C7D',
  },
  suyoTagPill: {
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  suyoTagPillText: {
    fontSize: 10.5,
    fontWeight: '700',
  },
  suyoTagUrgent: {
    backgroundColor: '#FEE2E2',
  },
  suyoTagUrgentText: {
    color: '#DC2626',
  },
  suyoTagToday: {
    backgroundColor: '#FEF3C7',
  },
  suyoTagTodayText: {
    color: '#D97706',
  },
  suyoTagNormal: {
    backgroundColor: '#E8F5EE',
  },
  suyoTagNormalText: {
    color: '#1E4D2B',
  },
  suyoTagTomorrow: {
    backgroundColor: '#E0F2FE',
  },
  suyoTagTomorrowText: {
    color: '#0369A1',
  },
  emptyStateBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: '#DFECE5',
    padding: 24,
    alignItems: 'center',
    gap: 8,
  },
  emptyStateTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#163523',
  },
  emptyStateSub: {
    fontSize: 12,
    color: '#718C7D',
    textAlign: 'center',
    lineHeight: 18,
  },
};
