export const mySuyoStyles = {
  mySuyoMainWrapper: {
    flex: 1,
    backgroundColor: '#FAFCFA',
  },
  mySuyoHeroSection: {
    backgroundColor: '#163925',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mySuyoHeroTextCol: {
    flex: 1,
    paddingRight: 12,
  },
  mySuyoHeroSuper: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#86EFAC',
    letterSpacing: 1.2,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  mySuyoHeroTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.4,
    marginBottom: 4,
  },
  mySuyoHeroSub: {
    fontSize: 12,
    color: '#C2DEC9',
    lineHeight: 16,
  },
  mySuyoHeroBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E8F5EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mySuyoTextNavWrapper: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#ECF4EF',
  },
  mySuyoTextNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 32,
  },
  mySuyoTextNavItem: {
    paddingVertical: 8,
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  mySuyoTextNavTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#7E9789',
    letterSpacing: -0.2,
  },
  mySuyoTextNavTitleActive: {
    fontWeight: '800',
    color: '#163523',
  },
  mySuyoTextNavCount: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8FA497',
  },
  mySuyoTextNavCountActive: {
    color: '#1E4D2B',
  },
  mySuyoTextNavUnderline: {
    position: 'absolute',
    bottom: -2,
    left: 0,
    right: 0,
    height: 2.5,
    borderRadius: 1.5,
    backgroundColor: '#1E4D2B',
  },
  mySuyoSubBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 10,
    backgroundColor: '#FAFCFA',
  },
  mySuyoSubBarTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 2,
  },
  mySuyoSubBarSubtitle: {
    fontSize: 11,
    color: '#658172',
  },
  mySuyoFadingEditText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: 'rgba(22, 53, 35, 0.45)',
    textDecorationLine: 'underline',
    textDecorationColor: 'rgba(22, 53, 35, 0.25)',
  },
  mySuyoSelectAllText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#DC2626',
  },
  mySuyoCardsList: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 24,
    backgroundColor: '#FAFCFA',
  },
  mySuyoCardItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1.2,
    borderColor: '#E2ECE6',
    shadowColor: '#163523',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  mySuyoCardItemSelected: {
    borderColor: '#F87171',
    backgroundColor: '#FFF9F9',
  },
  mySuyoSelectionCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#B0C7B9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  mySuyoSelectionCircleSelected: {
    backgroundColor: '#DC2626',
    borderColor: '#DC2626',
  },
  mySuyoCardSubRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  mySuyoCardStatusText: {
    fontSize: 12,
    fontWeight: '700',
  },
  mySuyoCardDateDot: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '700',
  },
  mySuyoCardDateText: {
    fontSize: 11.5,
    color: '#658172',
    fontWeight: '600',
  },
  mySuyoCardTitle: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#163523',
    lineHeight: 19,
    marginBottom: 4,
  },
  mySuyoCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F0F5F2',
  },
  mySuyoCardLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  mySuyoCardLocationText: {
    fontSize: 11,
    color: '#658172',
    fontWeight: '500',
  },
  mySuyoCardRewardText: {
    fontSize: 14.5,
    fontWeight: '900',
    color: '#1E4D2B',
  },
  mySuyoEmptyBox: {
    paddingVertical: 44,
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 8,
  },
  mySuyoEmptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#163523',
  },
  mySuyoEmptySub: {
    fontSize: 12,
    color: '#718C7D',
    textAlign: 'center',
    lineHeight: 17,
  },
  mySuyoEditFloatingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 16,
    marginTop: 6,
    marginBottom: 16,
  },
  mySuyoCancelEditBtn: {
    flex: 1,
    backgroundColor: '#F0F5F2',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  mySuyoCancelEditText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#52695C',
  },
  mySuyoConfirmDeleteBtn: {
    flex: 2,
    backgroundColor: '#DC2626',
    borderRadius: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  mySuyoConfirmDeleteBtnDisabled: {
    backgroundColor: '#E5ECE8',
  },
  mySuyoConfirmDeleteBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  mySuyoConfirmDeleteBtnTextDisabled: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#8CA395',
  },
};
