export const notificationsStyles = {
  notificationsModalCard: {
    width: '100%',
    maxWidth: 395,
    height: '78%',
    maxHeight: '88%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 18,
    elevation: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
  },
  notifModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  notifTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  notifModalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#163523',
    letterSpacing: -0.3,
  },
  notifCountPill: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
  },
  notifCountText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#DC2626',
  },
  notifTopActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF4F0',
  },
  notifFilterPillsWrap: {
    flexDirection: 'row',
    gap: 5,
  },
  notifFilterPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: '#F3F8F5',
    borderWidth: 1,
    borderColor: '#DFECE5',
  },
  notifFilterPillActive: {
    backgroundColor: '#1E4D2B',
    borderColor: '#1E4D2B',
  },
  notifFilterPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#52695C',
  },
  notifFilterPillTextActive: {
    color: '#FFFFFF',
  },
  notifMarkAllReadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 3.5,
    borderRadius: 8,
    backgroundColor: '#EBF5EF',
  },
  notifMarkAllReadText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1E4D2B',
  },
  notifScrollList: {
    flex: 1,
    marginBottom: 8,
  },
  notifSwipeContainer: {
    position: 'relative',
    marginBottom: 8,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#DC2626',
  },
  notifDeleteActionBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: 75,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    zIndex: 1,
  },
  notifDeleteActionText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  notifCardItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8F0EC',
    zIndex: 2,
  },
  notifCardInnerTouch: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 9,
    paddingHorizontal: 11,
    gap: 9,
    width: '100%',
  },
  notifCardItemUnread: {
    backgroundColor: '#F4FAF6',
    borderColor: '#CCE6D7',
  },
  notifCardLeftCol: {
    paddingTop: 1,
  },
  notifIconCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifIconDoer: {
    backgroundColor: '#E6F4EC',
  },
  notifIconTask: {
    backgroundColor: '#ECFDF5',
  },
  notifIconPayment: {
    backgroundColor: '#FEF3C7',
  },
  notifIconNearby: {
    backgroundColor: '#E0F2FE',
  },
  notifCardContentCol: {
    flex: 1,
  },
  notifCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  notifCardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#163523',
  },
  notifCardTime: {
    fontSize: 10,
    color: '#8CA094',
    fontWeight: '600',
  },
  notifCardBody: {
    fontSize: 11.5,
    color: '#476353',
    lineHeight: 16,
    marginBottom: 4,
  },
  notifCardBottomActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notifActionLinkText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#1E4D2B',
  },
  notifSwipeHintText: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontWeight: '500',
  },
  notifTrashIconBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifMarkSingleReadBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#EBF4EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifEmptyBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
    paddingHorizontal: 20,
    gap: 8,
  },
  notifEmptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#163523',
    marginTop: 4,
  },
  notifEmptySub: {
    fontSize: 12.5,
    color: '#718C7D',
    textAlign: 'center',
    lineHeight: 18,
  },
  notifModalBottomRow: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#EEF4F0',
  },
  notifClearBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
  },
  notifClearBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
  },
  notifDoneBtn: {
    flex: 1.5,
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifDoneBtnText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
