import { Platform } from 'react-native';

export const receiptStyles = {
  receiptModalCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    overflow: 'hidden',
  },
  receiptModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2ECE5',
    backgroundColor: '#F8FAF9',
  },
  receiptHeaderBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptModalHeaderTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#163523',
  },
  receiptScrollContent: {
    padding: 16,
  },
  receiptTicketBox: {
    backgroundColor: '#FAFCFA',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#D7EBE0',
    marginBottom: 16,
  },
  receiptBrandTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#163523',
    letterSpacing: 1,
    textAlign: 'center',
  },
  receiptBrandTag: {
    fontSize: 11,
    color: '#059669',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 4,
  },
  receiptRefDisplay: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginBottom: 12,
  },
  receiptDashedLine: {
    borderBottomWidth: 1,
    borderBottomColor: '#CBD5E1',
    borderStyle: 'dashed',
    marginVertical: 10,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  receiptLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  receiptValue: {
    fontSize: 12.5,
    color: '#163523',
    fontWeight: '600',
  },
  receiptTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#E8F5EE',
    borderRadius: 10,
    padding: 10,
    marginTop: 6,
    marginBottom: 10,
  },
  receiptTotalLabel: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#163523',
  },
  receiptTotalValue: {
    fontSize: 16,
    fontWeight: '900',
    color: '#15803D',
  },
  receiptProofBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    borderRadius: 10,
    padding: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    marginBottom: 12,
  },
  receiptProofTitle: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#15803D',
  },
  receiptProofSub: {
    fontSize: 10.5,
    color: '#557261',
    lineHeight: 14,
  },
  receiptBarcodeBox: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  receiptBarcodeBars: {
    width: '75%',
    height: 24,
    backgroundColor: '#1E293B',
    borderRadius: 3,
    marginBottom: 4,
    opacity: 0.85,
  },
  receiptBarcodeText: {
    fontSize: 10.5,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: '#64748B',
    letterSpacing: 2,
  },
  receiptActionsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 8,
  },
  receiptShareActionBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5EE',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: '#CDE5D7',
  },
  receiptShareActionBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#163523',
  },
  receiptCloseActionBtn: {
    flex: 1,
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptCloseActionBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
