export const statisticsStyles = {
  statsModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingVertical: 18,
    paddingHorizontal: 18,
    width: '92%',
    maxWidth: 420,
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  statsScrollView: {
    flexShrink: 1,
    width: '100%',
  },
  statsIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsMetricsGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  statsMetricTile: {
    flex: 1,
    backgroundColor: '#F8FAF9',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#EDF5F0',
  },
  statsTileValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 1,
  },
  statsTileLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#557261',
    marginBottom: 1,
  },
  statsTileSub: {
    fontSize: 9.5,
    fontWeight: '500',
    color: '#7A9384',
  },
  statsCategoryCard: {
    backgroundColor: '#F8FAF9',
    borderRadius: 14,
    padding: 12,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#EDF5F0',
  },
  statsCategoryHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statsSectionHeading: {
    fontSize: 13,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 1,
  },
  statsSectionSubheading: {
    fontSize: 10.5,
    color: '#7A9384',
  },
  statsInfoNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F0FDF4',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  statsInfoNoticeText: {
    fontSize: 10.5,
    color: '#15803D',
    lineHeight: 15,
    flex: 1,
    fontWeight: '500',
  },
  statsDoneButton: {
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 11,
  },
  statsDoneButtonText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  statsSatisfactionScoreBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 7,
    paddingVertical: 3.5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  statsSatisfactionScoreText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#92400E',
  },
  csatBarsContainer: {
    marginTop: 8,
    marginBottom: 8,
    gap: 5,
  },
  csatBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  csatStarLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 24,
    justifyContent: 'flex-start',
    gap: 2,
  },
  csatStarText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#334155',
  },
  csatTrack: {
    flex: 1,
    height: 7,
    backgroundColor: '#E2E8F0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  csatFill: {
    height: '100%',
    borderRadius: 4,
  },
  csatPctText: {
    width: 58,
    fontSize: 10,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'right',
  },
  csatHighlightsRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 3,
  },
  csatHighlightChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 6,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  csatHighlightText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#166534',
  },
};
