export const suyoDetailsStyles = {
  suyoDetailModalCard: {
    width: '100%',
    maxWidth: 390,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    elevation: 10,
  },
  detailTopMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  detailTopMetaLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flex: 1,
  },
  detailTopMetaRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailPostedTimeText: {
    fontSize: 12,
    color: '#658172',
    fontWeight: '600',
  },
  detailTitleAndStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  detailCardTitleInRow: {
    fontSize: 17.5,
    fontWeight: '800',
    color: '#163523',
    lineHeight: 23,
    flex: 1,
  },
  detailStatusPillInline: {
    paddingVertical: 4.5,
    paddingHorizontal: 10,
    borderRadius: 8,
    alignSelf: 'center',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailStatusPillInlineText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  detailHeartBtn: {
    padding: 4,
  },
  detailDivider: {
    height: 1,
    backgroundColor: '#EEF4F0',
    marginVertical: 12,
  },
  detailRequestorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailRequestorLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  detailAvatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1E4D2B',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  detailAvatarInitials: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    includeFontPadding: false,
    lineHeight: 18,
  },
  detailRequestorTextCol: {
    flex: 1,
  },
  detailRequestorName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 2,
  },
  detailRequestorMeta: {
    fontSize: 11.5,
    color: '#718C7D',
    marginBottom: 2,
  },
  detailRequestorPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  detailRequestorPhoneText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#4B6354',
  },
  detailRequestorCallBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EBF5EE',
    borderWidth: 1.5,
    borderColor: '#C2E0CC',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  detailRequestorEditBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E8F5EE',
    borderWidth: 1.5,
    borderColor: '#C2E0CC',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  detailStatsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  detailStatCol: {
    flex: 1,
  },
  detailStatLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#7E9789',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  detailRewardAmount: {
    fontSize: 22,
    fontWeight: '900',
    color: '#163523',
  },
  detailLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  detailLocationName: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#163523',
  },
  detailTaskHeading: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#163523',
  },
  detailTaskBody: {
    fontSize: 13,
    color: '#4B6354',
    lineHeight: 19,
    marginBottom: 14,
  },
  detailActionButtonsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  detailFulfillBtn: {
    flex: 2,
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  detailFulfillBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  detailCloseIconBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  detailDoerHighlightCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3FAF5',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#CDE5D6',
    gap: 10,
    marginBottom: 4,
  },
  detailDoerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1E4D2B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailDoerAvatarInitials: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  detailDoerTextCol: {
    flex: 1,
  },
  detailDoerNameText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#163523',
  },
  detailDoerMetaText: {
    fontSize: 11,
    color: '#607B6C',
    marginTop: 1,
  },
  detailDoerPhoneText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#425C4D',
    marginTop: 2,
  },
  detailBoostCard: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  detailBoostHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  detailBoostIconBox: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBoostTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#166534',
  },
  detailBoostSubtitle: {
    fontSize: 11,
    color: '#4B6354',
    lineHeight: 15,
  },
  detailBoostButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  detailBoostChip: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#86EFAC',
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBoostChipGreen: {
    backgroundColor: '#059669',
    borderColor: '#059669',
  },
  detailBoostChipText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#166534',
  },
  detailEditSuyoBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5EE',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 5,
  },
  detailEditSuyoBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#163523',
  },
  detailCancelSuyoBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 5,
  },
  detailCancelSuyoBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#DC2626',
  },
  detailCallDoerBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5EE',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: '#CDE5D7',
  },
  detailCallDoerBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#163523',
  },
  detailTrackCourierBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#059669',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
  },
  detailTrackCourierBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  detailArchiveSuyoBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 5,
  },
  detailArchiveSuyoBtnText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#334155',
  },
  detailPrimaryActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E4D2B',
    borderRadius: 14,
    paddingVertical: 13,
    gap: 8,
  },
  detailPrimaryActionBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  detailRepeatSuyoBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E4D2B',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
  },
  detailRepeatSuyoBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  detailArchiveSuyoBtnYellow: {
    backgroundColor: '#FDE047',
    borderColor: '#EAB308',
    borderWidth: 1.5,
  },
  detailArchiveSuyoBtnTextYellow: {
    color: '#78350F',
    fontWeight: '800',
  },
  detailAttachmentsSection: {
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: '#F8FAF9',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2ECE6',
  },
  detailAttachmentsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  detailAttachmentsHeading: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#163523',
  },
  detailAttachmentsScroll: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 2,
  },
  detailAttachmentChip: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  detailAttachmentImageWrap: {
    width: 72,
    height: 72,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E2E8F0',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  detailAttachmentThumb: {
    width: '100%',
    height: '100%',
  },
  detailAttachmentTag: {
    position: 'absolute',
    bottom: 3,
    left: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  detailAttachmentTagText: {
    fontSize: 8.5,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  detailAttachmentDocWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFDF5',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    maxWidth: 160,
  },
  detailAttachmentDocName: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#92400E',
    flex: 1,
  },
};
