import {
  getTodayFormatted,
  getTomorrowFormatted,
} from './legacyDashboardHelpers';

export const INITIAL_AVAILABLE_SUYOS = [
  {
    id: 'SYL-101',
    title: 'Drop off documents - Unit 402',
    category: 'Documents',
    location: 'Makati CBD',
    distance: 0.5,
    distanceText: '0.5 km away',
    reward: '₱300',
    rewardAmount: 300,
    tag: 'Urgent',
    postedTime: 'Just now',
    createdAt: Date.now() - 2 * 60 * 1000,
    due: 'Due today ASAP',
    dueDate: getTodayFormatted(),
    details:
      'Drop off notarized lease agreements and corporate papers at the 4th floor reception.',
    notes: 'Please hand directly to Ms. Santos.',
    requesterName: 'Atty. Rafael Cruz',
    requesterPhone: '0917 842 1983',
    requesterRating: '4.9★',
    completedCount: '34 completed',
  },
  {
    id: 'SYL-102',
    title: 'Buy groceries - SM Tagum',
    category: 'Groceries',
    location: 'SM Tagum',
    distance: 0.8,
    distanceText: '0.8 km away',
    reward: '₱150',
    rewardAmount: 150,
    tag: 'Due today',
    postedTime: '12 mins ago',
    createdAt: Date.now() - 12 * 60 * 1000,
    due: 'Due today at 5:00 PM',
    dueDate: getTodayFormatted(),
    details:
      '2 cartons of milk, 1 loaf of wheat bread, and 1 pack of eggs from supermarket.',
    notes: 'Receipt will be reimbursed via GCash or cash upon delivery.',
    requesterName: 'Maria Clarissa',
    requesterInitials: 'MR',
    requesterPhone: '0928 341 5520',
    requesterRating: '4.9★',
    completedCount: '34 completed',
  },
  {
    id: 'SYL-103',
    title: 'Queue for bills payment',
    category: 'Queuing & Bills',
    location: 'Bayad Center Ayala',
    distance: 1.4,
    distanceText: '1.4 km away',
    reward: '₱100',
    rewardAmount: 100,
    tag: 'Normal',
    postedTime: '35 mins ago',
    createdAt: Date.now() - 35 * 60 * 1000,
    due: 'Due tomorrow at 11:00 AM',
    dueDate: getTomorrowFormatted(),
    details:
      'Line up to pay Meralco electric bill. Cash is prepared in an envelope.',
    notes: 'Return validated slip to lobby desk.',
    requesterName: 'Kenneth Gomez',
    requesterPhone: '0919 720 9144',
    requesterRating: '4.8★',
    completedCount: '28 completed',
  },
  {
    id: 'SYL-104',
    title: 'Pick up birthday cake',
    category: 'Delivery',
    location: 'Goldilocks Poblacion',
    distance: 2.1,
    distanceText: '2.1 km away',
    reward: '₱220',
    rewardAmount: 220,
    tag: 'Due tomorrow',
    postedTime: '1 hour ago',
    createdAt: Date.now() - 60 * 60 * 1000,
    due: 'Due tomorrow at 2:00 PM',
    dueDate: getTomorrowFormatted(),
    details:
      'Pre-ordered 8-inch chocolate mousse cake. Needs upright, careful handling.',
    notes: 'Order #GLD-8821 under name Juan Dela Cruz.',
    requesterName: 'Patricia Tan',
    requesterPhone: '0905 188 4390',
    requesterRating: '5.0★',
    completedCount: '41 completed',
  },
  {
    id: 'SYL-105',
    title: 'Prescription pickup at Mercury Drug',
    category: 'Delivery',
    location: 'Mercury Drug Legaspi',
    distance: 1.1,
    distanceText: '1.1 km away',
    reward: '₱180',
    rewardAmount: 180,
    tag: 'Urgent',
    postedTime: '2 hours ago',
    createdAt: Date.now() - 120 * 60 * 1000,
    due: 'Due today ASAP',
    dueDate: getTodayFormatted(),
    details:
      'Pick up maintenance heart medication prescription for senior citizen.',
    notes: 'Prescription slip is with the pharmacist.',
    requesterName: 'Lola Remedios',
    requesterPhone: '0939 655 0122',
    requesterRating: '4.9★',
    completedCount: '19 completed',
  },
];

export const DEFAULT_DOER = {
  id: 'DOER-101',
  name: 'Alex Morales',
  initials: 'AM',
  phone: '+63 917 842 1983',
  rating: '4.95★',
  reviewCount: '142 reviews',
  completedCount: '142 suyos',
  vehicle: 'Honda Beat 125cc (Motorcycle)',
  vehiclePlate: 'ND-8821',
  badge: 'Top Rated Courier',
  onTimeRate: '99.2%',
  bio: 'Full-time motorcycle courier in Makati, BGC, and Tagum. Fast, reliable, and careful with parcels & documents.',
};

export const INITIAL_POSTED_SUYOS = [
  {
    id: 'POST-001',
    title: 'Buy groceries - SM Tagum',
    category: 'Groceries',
    location: 'SM Tagum',
    distanceText: '0.8 km away',
    reward: '₱150',
    rewardAmount: 150,
    tag: 'Waiting for doer',
    status: 'Open - waiting for a doer',
    urgency: 'Due today',
    due: 'Due today at 5:00 PM',
    dueDate: getTodayFormatted(),
    createdAt: Date.now() - 45 * 60 * 1000,
    formattedDate: 'Sep 28 · 11:20 AM',
    waitTime: 'Waiting for 45m',
    needsBoost: true,
    details:
      '2 cartons of milk, 1 loaf of wheat bread, and 1 pack of eggs from supermarket.',
    notes: 'Receipt will be reimbursed via GCash or cash upon delivery.',
    requesterName: 'Juan Dela Cruz (You)',
  },
  {
    id: 'POST-002',
    title: 'Package pickup and drop-off at LBC Glorietta',
    category: 'Delivery',
    location: 'LBC Express - Glorietta',
    distanceText: '1.6 km away',
    reward: '₱160',
    rewardAmount: 160,
    tag: 'Waiting for doer',
    status: 'Open - waiting for a doer',
    urgency: 'Due tomorrow',
    due: 'Due tomorrow at 2:00 PM',
    dueDate: getTomorrowFormatted(),
    createdAt: Date.now() - 25 * 60 * 1000,
    formattedDate: 'Today · 5:15 PM',
    waitTime: 'Waiting for 25m',
    needsBoost: true,
    details:
      'Drop off pre-packed box with return barcode sticker at LBC branch.',
    notes: 'Already prepaid, just drop off at counter 2.',
    requesterName: 'Juan Dela Cruz (You)',
  },
];

export const INITIAL_CANCELLED_SUYOS = [
  {
    id: 'POST-003',
    title: 'Pick up documents',
    category: 'Documents',
    location: 'Makati CBD',
    distanceText: '1.2 km away',
    reward: '₱200',
    rewardAmount: 200,
    tag: 'Cancelled',
    status: 'Cancelled',
    urgency: 'Normal',
    due: 'Cancelled',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    formattedDate: 'Sep 22 · 3:40 PM',
    details: 'Pick up notarized contract copy from law office at 5th floor.',
    notes: 'Cancelled by requester due to rescheduled meeting.',
    requesterName: 'Juan Dela Cruz (You)',
  },
];

export const INITIAL_ACCEPTED_SUYOS = [
  {
    id: 'ACC-001',
    title: 'Drop off documents - Unit 402',
    category: 'Documents',
    location: 'Makati CBD',
    distanceText: '0.5 km away',
    reward: '₱300',
    rewardAmount: 300,
    tag: 'In Progress',
    status: 'In Progress - On the way',
    createdAt: Date.now() - 35 * 60 * 1000,
    formattedDate: 'Today · 4:00 PM',
    details:
      'Drop off notarized lease agreements and corporate papers at 4th floor reception.',
    notes: 'Please hand directly to Ms. Santos.',
    requesterName: 'Juan Dela Cruz (You)',
    doer: {
      id: 'DOER-101',
      name: 'Alex Morales',
      initials: 'AM',
      phone: '+63 917 842 1983',
      rating: '4.95★',
      reviewCount: '142 reviews',
      completedCount: '142 suyos',
      vehicle: 'Honda Beat 125cc (Motorcycle)',
      vehiclePlate: 'ND-8821',
      badge: 'Top Rated Courier',
      onTimeRate: '99.2%',
      bio: 'Full-time motorcycle courier in Makati, BGC, and Tagum. Fast, reliable, and careful with parcels.',
    },
  },
  {
    id: 'ACC-002',
    title: 'Buy fresh groceries and bread at Landmark',
    category: 'Groceries',
    location: 'Landmark Supermarket',
    distanceText: '0.8 km away',
    reward: '₱200',
    rewardAmount: 200,
    tag: 'In Progress',
    status: 'In Progress - Shopping',
    createdAt: Date.now() - 90 * 60 * 1000,
    formattedDate: 'Today · 2:30 PM',
    details: '2 cartons oat milk, 1 loaf whole wheat bread, 1 tray fresh eggs.',
    notes: 'Please check expiration date before purchasing.',
    requesterName: 'Juan Dela Cruz (You)',
    doer: {
      id: 'DOER-102',
      name: 'Maria Clarissa',
      initials: 'MC',
      phone: '+63 928 341 5520',
      rating: '4.88★',
      reviewCount: '89 reviews',
      completedCount: '89 suyos',
      vehicle: 'Bicycle Courier',
      vehiclePlate: 'BIKE-04',
      badge: 'Verified Suyo Courier',
      onTimeRate: '98.5%',
      bio: 'Eco-friendly bicycle courier servicing Greenbelt and Legazpi village.',
    },
  },
];

export const INITIAL_COMPLETED_SUYOS = [
  {
    id: 'COMP-001',
    title: 'Print school project',
    category: 'Documents',
    location: 'Davao Printing Hub',
    distanceText: '1.5 km away',
    reward: '₱80',
    rewardAmount: 80,
    tag: 'Completed',
    status: 'Completed',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    formattedDate: 'Sep 20 · 3:15 PM',
    completedDate: 'Sep 20, 2026 at 3:15 PM',
    details: 'Full color printing and ring binding of 45-page thesis project.',
    notes: 'Completed ahead of schedule.',
    requesterName: 'Juan Dela Cruz (You)',
    doer: {
      id: 'DOER-103',
      name: 'Carlos Dalisay',
      initials: 'CD',
      phone: '+63 919 720 9144',
      rating: '4.9★',
      reviewCount: '210 reviews',
      completedCount: '210 suyos',
      vehicle: 'Yamaha Mio (Motorcycle)',
      vehiclePlate: 'DC-9912',
      badge: 'Community Hero',
      onTimeRate: '99.5%',
      bio: 'Dependable community courier with over 200+ completed local suyos.',
    },
  },
  {
    id: 'COMP-002',
    title: 'Pick up medical supplies from Mercury Drug',
    category: 'Delivery',
    location: 'Mercury Drug Legaspi',
    distanceText: '1.1 km away',
    reward: '₱180',
    rewardAmount: 180,
    tag: 'Completed',
    status: 'Completed',
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    formattedDate: 'Sep 23 · 11:40 AM',
    completedDate: 'Sep 23, 2026 at 11:40 AM',
    details: 'Pick up prescribed maintenance asthma medication and vitamins.',
    notes: 'Delivered directly to reception desk.',
    requesterName: 'Juan Dela Cruz (You)',
    doer: {
      id: 'DOER-101',
      name: 'Alex Morales',
      initials: 'AM',
      phone: '+63 917 842 1983',
      rating: '4.95★',
      reviewCount: '142 reviews',
      completedCount: '142 suyos',
      vehicle: 'Honda Beat 125cc (Motorcycle)',
      vehiclePlate: 'ND-8821',
      badge: 'Top Rated Courier',
      onTimeRate: '99.2%',
      bio: 'Full-time motorcycle courier in Makati, BGC, and Tagum.',
    },
  },
  {
    id: 'COMP-003',
    title: 'Queue for Meralco electric bill payment',
    category: 'Queuing & Bills',
    location: 'Bayad Center Ayala',
    distanceText: '1.4 km away',
    reward: '₱150',
    rewardAmount: 150,
    tag: 'Completed',
    status: 'Completed',
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    formattedDate: 'Sep 28 · 1:10 PM',
    completedDate: 'Sep 28, 2026 at 1:10 PM',
    details: 'Pay monthly electricity bill before 4 PM counter cut-off.',
    notes: 'Validated payment slip returned.',
    requesterName: 'Juan Dela Cruz (You)',
    doer: {
      id: 'DOER-104',
      name: 'Kenneth Gomez',
      initials: 'KG',
      phone: '+63 905 188 4390',
      rating: '5.0★',
      reviewCount: '64 reviews',
      completedCount: '64 suyos',
      vehicle: 'Walking / Commute',
      vehiclePlate: 'COMMUTER',
      badge: 'Queuing Specialist',
      onTimeRate: '100%',
      bio: 'Specialist in government agency and utility bills queuing.',
    },
  },
];

export const INITIAL_ARCHIVED_SUYOS = [
  {
    id: 'ARCH-001',
    title: 'Weekly SM Supermarket Grocery Run',
    category: 'Groceries',
    location: 'SM Tagum',
    distanceText: '0.8 km away',
    reward: '₱180',
    rewardAmount: 180,
    tag: 'Archived Template',
    status: 'Archived Template',
    createdAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
    formattedDate: 'Saved · Sep 18, 9:15 AM',
    details:
      'Standard weekly supply: 2 cartons milk, 1 loaf whole wheat bread, eggs, fruit.',
    notes: 'Reimbursement upon delivery receipt.',
    requesterName: 'Juan Dela Cruz (You)',
  },
  {
    id: 'ARCH-002',
    title: 'Monthly Electric Bill Bayad Center',
    category: 'Queuing & Bills',
    location: 'Bayad Center Ayala',
    distanceText: '1.4 km away',
    reward: '₱150',
    rewardAmount: 150,
    tag: 'Archived Template',
    status: 'Archived Template',
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    formattedDate: 'Saved · Sep 15, 1:20 PM',
    details: 'Pay monthly electricity bill with prepared cash envelope.',
    notes: 'Return receipt to lobby guard.',
    requesterName: 'Juan Dela Cruz (You)',
  },
  {
    id: 'ARCH-003',
    title: 'Emergency Maintenance Medicine Pickup',
    category: 'Delivery',
    location: 'Mercury Drug Legaspi',
    distanceText: '1.1 km away',
    reward: '₱160',
    rewardAmount: 160,
    tag: 'Archived Template',
    status: 'Archived Template',
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    formattedDate: 'Saved · Aug 29, 10:45 AM',
    details: 'Maintenance prescription pickup from pharmacy counter.',
    notes: 'Senior citizen discount book is at pharmacy.',
    requesterName: 'Juan Dela Cruz (You)',
  },
];

export const INITIAL_DOER_ACCEPTED_SUYOS = [
  {
    id: 'DOER-ACC-01',
    title: 'Express pharmacy pickup at Mercury Drug',
    category: 'Medicine',
    icon: 'medkit',
    location: 'Mercury Drug Legaspi, Makati',
    distanceText: '1.2 km away',
    reward: '₱180.00',
    rewardAmount: 180,
    status: 'Accepted - In Progress',
    tag: 'In Progress',
    acceptedAt: 'Today · 1:15 PM',
    deadline: 'Today · By 3:00 PM',
    requesterName: 'Lola Remedios',
    requesterPhone: '0918 342 9811',
    details:
      'Pick up maintenance medicine (Losartan and Metformin). Senior citizen booklet is at the pharmacy counter.',
    notes: 'Please call Lola Remedios upon arriving at the building lobby.',
  },
  {
    id: 'DOER-ACC-02',
    title: 'Drop off sealed documents at Tower 2',
    category: 'Documents',
    icon: 'document-text',
    location: 'Makati CBD, Tower 2 Reception',
    distanceText: '0.6 km away',
    reward: '₱120.00',
    rewardAmount: 120,
    status: 'Accepted - In Progress',
    tag: 'In Progress',
    acceptedAt: 'Today · 2:00 PM',
    deadline: 'Today · By 4:30 PM',
    requesterName: 'Patricia Mendoza',
    requesterPhone: '0922 841 0293',
    details: 'Drop off sealed envelope to Atty. Gabriel on 12th Floor.',
    notes: 'Sign recipient visitor log at front desk.',
  },
];

export const INITIAL_DOER_CANCELLED_SUYOS = [
  {
    id: 'DOER-CAN-01',
    title: 'Buy medicine at Mercury Drug Tagum',
    category: 'Medicine',
    icon: 'medkit',
    location: 'Mercury Drug Pioneer, Tagum City',
    distanceText: '1.4 km away',
    reward: '₱160.00',
    rewardAmount: 160,
    status: 'Cancelled',
    tag: 'Cancelled',
    requesterName: 'Tita Gloria',
    requesterPhone: '0917 482 9102',
    cancelledAt: 'Yesterday · 5:20 PM',
    reason: 'Vehicle broke down on route',
    details:
      'Maintenance vitamins and cough syrup. Senior citizen booklet is at the pharmacy counter.',
    notes: 'Cancelled due to flat tire. Notified requester immediately.',
  },
  {
    id: 'DOER-CAN-02',
    title: 'Deliver bakery boxes to Visayan Village',
    category: 'Food & Pastries',
    icon: 'fast-food',
    location: 'Tagum City Commercial Center',
    distanceText: '2.1 km away',
    reward: '₱140.00',
    rewardAmount: 140,
    status: 'Cancelled',
    tag: 'Cancelled',
    requesterName: 'Bakery Co.',
    requesterPhone: '0922 711 0932',
    cancelledAt: 'Oct 1 · 10:45 AM',
    reason: 'Store closed early',
    details: 'Pick up 2 pastry boxes and drop off at Visayan Village.',
    notes: 'Requester cancelled order because store kitchen had closed.',
  },
];

export const WALLET_EARNED_SUYOS = [
  {
    id: 'WAL-001',
    title: 'Drop off documents - Unit 402',
    category: 'Documents',
    icon: 'document-text',
    date: 'Today (W4) · 4:00 PM',
    requesterName: 'Atty. Rafael Cruz',
    location: 'Makati CBD, Tower 1',
    earnedAmount: 300,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-9842',
  },
  {
    id: 'WAL-002',
    title: 'Express parcel delivery to Greenbelt',
    category: 'Delivery',
    icon: 'bicycle',
    date: 'Today (W4) · 10:00 AM',
    requesterName: 'Patricia Mendoza',
    location: 'Greenbelt 5 Concierge',
    earnedAmount: 90,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-9801',
  },
  {
    id: 'WAL-003',
    title: 'Buy groceries - SM Tagum',
    category: 'Groceries',
    icon: 'cart',
    date: 'Oct 20 (W3) · 12:15 PM',
    requesterName: 'Maria Clarissa',
    location: 'SM Tagum Supermarket',
    earnedAmount: 150,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-9755',
  },
  {
    id: 'WAL-004',
    title: 'Queue for Meralco bills payment',
    category: 'Queuing & Bills',
    icon: 'time',
    date: 'Oct 17 (W3) · 11:30 AM',
    requesterName: 'Kenneth Gomez',
    location: 'Bayad Center Ayala',
    earnedAmount: 180,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-9510',
  },
  {
    id: 'WAL-005',
    title: 'Print school project & binding',
    category: 'Documents',
    icon: 'print',
    date: 'Oct 13 (W2) · 4:15 PM',
    requesterName: 'Dave B. (Student)',
    location: 'Davao Printing Hub',
    earnedAmount: 160,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-9321',
  },
  {
    id: 'WAL-006',
    title: 'Prescription pickup at Mercury Drug',
    category: 'Medicine',
    icon: 'medkit',
    date: 'Oct 10 (W2) · 3:45 PM',
    requesterName: 'Lola Remedios',
    location: 'Mercury Drug Legaspi',
    earnedAmount: 180,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-9120',
  },
  {
    id: 'WAL-007',
    title: 'Pick up medical supplies & vitamins',
    category: 'Delivery',
    icon: 'bag-check-outline',
    date: 'Oct 04 (W1) · 10:00 AM',
    requesterName: 'Mrs. Angela Santos',
    location: 'Generika Drugstore',
    earnedAmount: 220,
    status: 'Received',
    paymentMethod: 'Direct Payment (Cash/P2P)',
    refNo: 'SYL-EARN-8940',
  },
];

export const INITIAL_ACTIVITY_RECORDS = [
  {
    id: 'ACT-001',
    refNo: 'SYL-REC-9842',
    title: 'Drop off documents - Unit 402',
    category: 'Documents',
    icon: 'document-text',
    date: 'Today · 4:00 PM',
    timestamp: Date.now() - 30 * 60 * 1000,
    role: 'requester',
    status: 'In Progress',
    amount: 300,
    platformFee: 20,
    totalAmount: 320,
    paymentMethod: 'GCash',
    paymentRef: 'GC-9842109841',
    doer: {
      name: 'Alex Morales',
      rating: '4.95★',
      phone: '+63 917 842 1983',
      vehicle: 'Honda Beat 125cc (Motorcycle)',
    },
    location: 'Makati CBD',
    hasProof: false,
    notes: 'Urgent contract document hand-off. Courier currently en route.',
  },
  {
    id: 'ACT-002',
    refNo: 'SYL-REC-9801',
    title: 'Buy groceries - SM Tagum',
    category: 'Groceries',
    icon: 'cart',
    date: 'Sep 28, 2026 · 12:15 PM',
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    role: 'requester',
    status: 'Completed',
    amount: 150,
    platformFee: 15,
    totalAmount: 165,
    paymentMethod: 'GCash',
    paymentRef: 'GC-8812903412',
    doer: {
      name: 'Alex Morales',
      rating: '4.95★',
      phone: '+63 917 842 1983',
      vehicle: 'Honda Beat 125cc (Motorcycle)',
    },
    location: 'SM Tagum',
    hasProof: true,
    proofDetails:
      'Official supermarket register receipt & packed grocery bags verified.',
    notes: '2 cartons milk, wheat bread, and eggs delivered fresh.',
  },
  {
    id: 'ACT-003',
    refNo: 'SYL-REC-9755',
    title: 'Prescription pickup at Mercury Drug',
    category: 'Medicine',
    icon: 'medkit',
    date: 'Sep 26, 2026 · 3:45 PM',
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    role: 'doer',
    status: 'Completed',
    amount: 180,
    platformFee: 0,
    totalAmount: 180,
    paymentMethod: 'SuyoLink Wallet',
    paymentRef: 'SW-771920391',
    requesterName: 'Lola Remedios',
    requesterRating: '4.9★',
    location: 'Mercury Drug Legaspi',
    hasProof: true,
    proofDetails:
      'Official pharmacy receipt & sealed prescription bag verified.',
    notes: 'Delivered maintenance cardiac medicine safely to senior citizen.',
  },
  {
    id: 'ACT-004',
    refNo: 'SYL-REC-9620',
    title: 'Print school project & binding',
    category: 'Documents',
    icon: 'print',
    date: 'Sep 20, 2026 · 3:15 PM',
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    role: 'requester',
    status: 'Completed',
    amount: 80,
    platformFee: 10,
    totalAmount: 90,
    paymentMethod: 'Cash on Delivery',
    paymentRef: 'COD-66210984',
    doer: {
      name: 'Carlos Dalisay',
      rating: '4.9★',
      phone: '+63 919 720 9144',
      vehicle: 'Yamaha Mio',
    },
    location: 'Davao Printing Hub',
    hasProof: true,
    proofDetails: 'Photo of bound 45-page thesis document verified.',
    notes: 'Delivered ahead of deadline, cleanly bound with cover sleeve.',
  },
  {
    id: 'ACT-005',
    refNo: 'SYL-REC-9510',
    title: 'Queue for Meralco bills payment',
    category: 'Queuing & Bills',
    icon: 'time',
    date: 'Sep 18, 2026 · 11:30 AM',
    timestamp: Date.now() - 12 * 24 * 60 * 60 * 1000,
    role: 'doer',
    status: 'Completed',
    amount: 250,
    platformFee: 0,
    totalAmount: 250,
    paymentMethod: 'SuyoLink Wallet',
    paymentRef: 'SW-651098231',
    requesterName: 'Kenneth Gomez',
    requesterRating: '4.8★',
    location: 'Bayad Center Ayala',
    hasProof: true,
    proofDetails: 'Machine-validated payment stamp slip photographed.',
    notes: 'Queued for 35 minutes, validated slip handed to client lobby desk.',
  },
  {
    id: 'ACT-006',
    refNo: 'SYL-REC-9402',
    title: 'Pick up notarized contract copy',
    category: 'Documents',
    icon: 'close-circle',
    date: 'Sep 15, 2026 · 2:10 PM',
    timestamp: Date.now() - 15 * 24 * 60 * 60 * 1000,
    role: 'requester',
    status: 'Refunded',
    amount: 200,
    platformFee: 0,
    totalAmount: 200,
    paymentMethod: 'GCash (Refunded)',
    paymentRef: 'REF-55102948',
    location: 'Makati CBD',
    hasProof: false,
    notes:
      'Cancelled due to lawyer rescheduling. 100% refund credited back to GCash.',
  },
];

export const CATEGORY_OPTIONS = [
  'All',
  'Delivery',
  'Groceries',
  'Documents',
  'Queuing & Bills',
  'Household',
];
export const URGENCY_OPTIONS = [
  'All',
  'Normal',
  'Urgent',
  'Due today',
  'Due tomorrow',
];

export const CATEGORY_CONFIG = {
  All: {
    gradient: ['#1E4D2B', '#163523'],
    border: '#1E4D2B',
    text: '#FFFFFF',
  },
  default: {
    gradient: ['#EAF4EF', '#D7EBE0'],
    border: '#B8DCC8',
    text: '#1E4D2B',
  },
};

export const URGENCY_CONFIG = {
  All: {
    gradient: ['#1E4D2B', '#163523'],
    border: '#1E4D2B',
    text: '#FFFFFF',
  },
  Normal: {
    gradient: ['#F1F5F9', '#E2E8F0'],
    border: '#CBD5E1',
    text: '#475569',
  },
  Urgent: {
    gradient: ['#FEE2E2', '#FECACA'],
    border: '#FCA5A5',
    text: '#B91C1C',
  },
  'Due today': {
    gradient: ['#FFEDD5', '#FED7AA'],
    border: '#FDBA74',
    text: '#C2410C',
  },
  'Due tomorrow': {
    gradient: ['#FEFCE8', '#FEF9C3'],
    border: '#FDE047',
    text: '#854D0E',
  },
};
