import { StyleSheet } from 'react-native';
export default StyleSheet.create({
  content: {
    padding: 20,
    paddingBottom: 36,
    gap: 18,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hero: { padding: 24, borderRadius: 26, gap: 24, overflow: 'hidden' },
  orbit: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderWidth: 1,
    borderRadius: 120,
    top: -110,
    right: -130,
    opacity: 0.15,
  },
  heroIdentity: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  avatar: {
    width: 76,
    height: 76,
    borderRadius: 25,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroStats: { flexDirection: 'row', borderTopWidth: 1, paddingTop: 20 },
  stat: { flex: 1, alignItems: 'center', gap: 5 },
  statValue: { fontSize: 21, fontWeight: '700' },
  card: { padding: 20, borderRadius: 22, borderWidth: 1 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: { fontSize: 17, fontWeight: '700', flexShrink: 1 },
  description: { fontSize: 12, lineHeight: 18 },
  edit: {
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingTop: 20,
  },
  label: { fontSize: 11, fontWeight: '500' },
  detailValue: { fontSize: 14, lineHeight: 21 },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    minHeight: 50,
  },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  shortcut: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  shortcutIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appearance: {
    flex: 1,
    paddingVertical: 18,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    gap: 8,
  },
  count: { minWidth: 28, padding: 6, borderRadius: 9, alignItems: 'center' },
  review: { borderTopWidth: 1, paddingTop: 18, marginTop: 18, gap: 12 },
  empty: { paddingTop: 26, paddingBottom: 12, alignItems: 'center', gap: 10 },
  emptyIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  notice: {
    padding: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  signout: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  footer: { textAlign: 'center', fontSize: 11, marginTop: 4 },
});
