import { StyleSheet } from 'react-native';
import { FIXED_COLORS } from '../../theme/colors';

export const createAccountStyles = (colors) =>
  StyleSheet.create({
    safeContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerBar: {
      height: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      backgroundColor: colors.background,
    },
    headerIconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: -0.3,
    },
    scrollContainer: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 18,
      paddingTop: 10,
    },

    /* NOTICES */
    errorNotice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.dangerSurface,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
      padding: 12,
      borderRadius: 14,
      marginBottom: 12,
    },
    errorNoticeText: {
      fontSize: 13,
      color: colors.danger,
      fontWeight: '600',
      flex: 1,
    },
    successNotice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.successSurface,
      borderWidth: 1,
      borderColor: colors.successBorder,
      padding: 12,
      borderRadius: 14,
      marginBottom: 12,
    },
    successNoticeText: {
      fontSize: 13,
      color: colors.success,
      fontWeight: '700',
      flex: 1,
    },

    /* MAIN PROFILE CARD */
    mainProfileCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      borderWidth: 1.5,
      borderColor: colors.border,
      padding: 22,
      alignItems: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 2,
    },
    avatarWrapper: {
      position: 'relative',
      marginBottom: 14,
    },
    avatarCircle: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 2,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    shinyVerifiedBadge: {
      position: 'absolute',
      bottom: -2,
      right: -2,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: FIXED_COLORS.verifiedGreen,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2.5,
      borderColor: colors.card,
      shadowColor: FIXED_COLORS.verifiedGreen,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.45,
      shadowRadius: 5,
      elevation: 5,
    },
    avatarInitialsText: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.link,
      letterSpacing: -0.5,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    nameText: {
      fontSize: 22,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: -0.3,
    },
    handleText: {
      fontSize: 13.5,
      fontWeight: '500',
      color: colors.textMuted,
      marginBottom: 8,
    },
    phoneMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 16,
      backgroundColor: colors.surfaceAlt,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    phoneMetaText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
    },

    /* STATS PANEL */
    statsCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      width: '100%',
      marginBottom: 18,
    },
    statCol: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statDivider: {
      width: 1,
      height: 28,
      backgroundColor: colors.border,
    },
    statNumber: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.2,
    },
    ratingNumberRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statLabel: {
      fontSize: 11.5,
      fontWeight: '600',
      color: colors.textMuted,
      marginTop: 2,
    },

    /* BIO CONTAINER */
    bioContainer: {
      width: '100%',
      marginBottom: 18,
    },
    bioHeading: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.textSecondary,
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    bioBody: {
      fontSize: 13,
      color: colors.text,
      lineHeight: 18.5,
    },

    /* ACTION BUTTONS */
    editProfileButton: {
      width: '100%',
      height: 44,
      borderRadius: 16,
      backgroundColor: 'transparent',
      borderWidth: 1.2,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    editProfileButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    callProfileButton: {
      width: '100%',
      height: 44,
      borderRadius: 16,
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    callProfileButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.onPrimary,
    },

    /* FEEDBACK & RATINGS SECTION */
    feedbackSection: {
      marginTop: 22,
    },
    feedbackSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    sectionHeading: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 2,
    },
    feedbackSubheading: {
      fontSize: 12,
      color: colors.textMuted,
    },
    feedbackRatingBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.warningSurface,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
    },
    feedbackRatingBadgeText: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.warning,
    },
    feedbackList: {
      gap: 12,
    },
    feedbackCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 1,
    },
    feedbackCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    feedbackAuthorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
    },
    feedbackAvatarCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    feedbackAvatarInitials: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.onPrimary,
    },
    feedbackAuthorName: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    feedbackDateText: {
      fontSize: 10.5,
      color: colors.textMuted,
    },
    feedbackStarsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    feedbackCardRatingNum: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
      marginLeft: 3,
    },
    rateMarksRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 8,
    },
    rateMarkChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.successSurface,
      borderWidth: 1,
      borderColor: colors.successBorder,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
    },
    rateMarkChipText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.success,
    },
    feedbackCommentText: {
      fontSize: 12.5,
      color: colors.text,
      lineHeight: 18,
      fontStyle: 'italic',
    },

    /* EMPTY FEEDBACK STATE */
    feedbackEmptyCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      paddingVertical: 28,
      paddingHorizontal: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderStyle: 'dashed',
    },
    feedbackEmptyIconCircle: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    feedbackEmptyTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    feedbackEmptySub: {
      fontSize: 12.5,
      color: colors.textMuted,
      textAlign: 'center',
      lineHeight: 18,
      maxWidth: 280,
    },

    /* MODALS */
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.backdrop,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    editModalCard: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 22,
    },
    modalHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
    },
    inputFieldLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 5,
      marginTop: 10,
    },
    textInput: {
      backgroundColor: colors.input,
      borderWidth: 1.2,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 13.5,
      color: colors.text,
    },
    bioInput: {
      minHeight: 70,
    },
    modalButtonRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 20,
    },
    modalCancelButton: {
      flex: 1,
      height: 46,
      borderRadius: 14,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalCancelText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    modalSaveButton: {
      flex: 1,
      height: 46,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalSaveText: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.onPrimary,
    },
  });
