// Brand color stays fixed across both themes
export const PRIMARY = '#1E4D2B'; // Signature Hunter Green

export const light = {
    primary: PRIMARY,
    heroBackground: PRIMARY,
    heroText: '#FFFFFF',
    heroTextMuted: '#D4E8DC',
    background: '#FFFFFF',
    surface: '#F8FAF9',
    card: '#FFFFFF',
    text: '#163523',
    textMuted: '#658071',
    border: '#D8E5DF',
    danger: '#D32F2F',
    white: '#FFFFFF',
    brand: PRIMARY,
    hero: PRIMARY,
    onPrimary: '#FFFFFF',
    link: PRIMARY,
    muted: '#658071',
    textSecondary: '#658071',
    surfaceAlt: '#EAF2ED',
    input: '#FFFFFF',
    shadow: '#163523',
    accent: '#6BA17B',
};

export const dark = {
    primary: PRIMARY,
    heroBackground: PRIMARY,
    heroText: '#FFFFFF',
    heroTextMuted: '#D4E8DC',
    background: '#0E1A13',
    surface: '#16241C',
    card: '#1B2A21',
    text: '#EAF3ED',
    textMuted: '#8FA497',
    border: '#2A3B30',
    danger: '#F26B6B',
    white: '#FFFFFF',
    brand: PRIMARY,
    hero: PRIMARY,
    onPrimary: '#FFFFFF',
    link: '#B5D8BF',
    muted: '#8FA497',
    textSecondary: '#8FA497',
    surfaceAlt: '#263B2E',
    input: '#16241C',
    shadow: '#000000',
    accent: '#8DBE9A',
};
