export const deadlineStyles = {
  deadlineStatusSection: { gap: 12 },
  deadlineStatusHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  deadlineStatusActiveTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  deadlineStatusActiveTagText: { fontSize: 11, fontWeight: '700' },
  deadlineStatusSubtitle: { fontSize: 12, lineHeight: 18, color: '#556E60' },
  deadlineStatusChipsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  deadlineStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 44,
    maxWidth: '100%',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D4E2DA',
    backgroundColor: '#FAFDFB',
  },
  deadlineStatusChipText: {
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    color: '#163523',
  },
  deadlineStatusChipTextActive: { color: '#FFFFFF' },
  deadlineStatusExplainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  deadlineStatusExplainerText: { flex: 1, fontSize: 12, lineHeight: 18 },
};
