import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: 18,
    paddingHorizontal: 16,
    paddingBottom: 50,
  },
  formContainer: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    gap: 16,
  },

  /* HERO BANNER */
  heroBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF5EF',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#D4E8DC',
    gap: 14,
  },
  heroIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CDE3D5',
  },
  heroTextCol: {
    flex: 1,
  },
  heroTitle: {
    fontSize: 16.5,
    fontWeight: '800',
    color: '#163523',
    letterSpacing: -0.2,
    marginBottom: 2,
  },
  heroSub: {
    fontSize: 12,
    lineHeight: 17,
    color: '#466151',
  },

  /* QUICK PRESETS */
  templatesBlock: {
    gap: 8,
  },
  templatesHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: '#556E60',
    letterSpacing: 0.2,
    paddingHorizontal: 2,
  },
  templatesScroll: {
    gap: 8,
  },
  templateChip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#D6E6DC',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  templateChipText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#1E4D2B',
  },
  templateChipCreate: {
    backgroundColor: '#EBF5EF',
    borderColor: '#A4D1B8',
  },
  templateChipCreateText: {
    color: '#163523',
    fontWeight: '800',
  },

  /* GENERAL ERROR BANNER */
  generalErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 12,
    padding: 12,
  },
  generalErrorText: {
    fontSize: 12.5,
    color: '#DC2626',
    fontWeight: '600',
    flex: 1,
  },

  /* CARDS */
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1.2,
    borderColor: '#E1ECE5',
    padding: 16,
    gap: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardWithErrors: {
    borderColor: '#FECACA',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F5F2',
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#163523',
    letterSpacing: -0.2,
  },
  cardSubText: {
    fontSize: 12,
    color: '#556E60',
    lineHeight: 16,
    marginTop: -6,
  },

  /* FIELDS */
  fieldBlock: {
    gap: 6,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#243D2F',
  },
  fieldLabelError: {
    color: '#DC2626',
    fontWeight: '800',
  },
  counterText: {
    fontSize: 11,
    color: '#8EA296',
    fontWeight: '600',
  },
  requiredBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: '#DC2626',
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  inputWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAFDFB',
    borderWidth: 1.2,
    borderColor: '#D4E2DA',
    borderRadius: 12,
    paddingHorizontal: 10,
    minHeight: 48,
  },
  inputErrorBorder: {
    borderColor: '#DC2626',
    borderWidth: 1.6,
    backgroundColor: '#FEF2F2',
  },
  currencySymbolBadgeError: {
    backgroundColor: '#FEE2E2',
    borderRightColor: '#DC2626',
  },
  fieldErrorText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#DC2626',
    marginTop: 2,
  },
  leadingIcon: {
    marginRight: 6,
  },
  textInputInner: {
    flex: 1,
    fontSize: 12.5,
    color: '#163523',
    fontWeight: '500',
    paddingVertical: Platform.OS === 'ios' ? 8 : 4,
    paddingHorizontal: 0,
    minWidth: 0,
  },
  textareaWrapper: {
    backgroundColor: '#FAFDFB',
    borderWidth: 1.2,
    borderColor: '#D4E2DA',
    borderRadius: 12,
    padding: 12,
    minHeight: 84,
  },
  textareaInput: {
    fontSize: 12.5,
    color: '#163523',
    lineHeight: 18,
  },
  pickerTrailingButton: {
    paddingLeft: 6,
    paddingRight: 2,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* CATEGORY GRID */
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1.2,
  },
  categoryBtnActive: {
    backgroundColor: '#1E4D2B',
    borderColor: '#1E4D2B',
    shadowColor: '#1E4D2B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryBtnInactive: {
    backgroundColor: '#F5FAF7',
    borderColor: '#D4E4DC',
  },
  categoryBtnError: {
    borderColor: '#DC2626',
    backgroundColor: '#FEF2F2',
  },
  categoryBtnText: {
    fontSize: 12.5,
    fontWeight: '600',
  },
  categoryBtnTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  categoryBtnTextInactive: {
    color: '#264A35',
  },

  /* CURRENCY / REWARD */
  currencyInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAFDFB',
    borderWidth: 1.2,
    borderColor: '#D4E2DA',
    borderRadius: 12,
    overflow: 'hidden',
    height: 50,
  },
  currencySymbolBadge: {
    width: 48,
    height: '100%',
    backgroundColor: '#EBF5EF',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#D4E2DA',
  },
  currencySymbolText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E4D2B',
  },
  currencyInput: {
    flex: 1,
    paddingHorizontal: 14,
    fontSize: 17,
    fontWeight: '800',
    color: '#163523',
  },
  presetsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  presetsLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#637A6D',
    marginRight: 2,
  },
  presetPill: {
    backgroundColor: '#F3F8F5',
    borderWidth: 1,
    borderColor: '#D8E8DF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  presetPillActive: {
    backgroundColor: '#1E4D2B',
    borderColor: '#1E4D2B',
  },
  presetPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2D4E3A',
  },
  presetPillTextActive: {
    color: '#FFFFFF',
  },

  /* DATE & TIME ROW */
  dateTimeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  dateTimeCol: {
    flex: 1,
    gap: 6,
  },
  dateTimeInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAFDFB',
    borderWidth: 1.2,
    borderColor: '#D4E2DA',
    borderRadius: 12,
    paddingHorizontal: 10,
    height: 48,
  },
  deadlineContainerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EBF5EF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  deadlinePillText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#1E4D2B',
  },

  /* LOAD ERROR */
  errorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 14,
    padding: 12,
  },
  errorCardText: {
    fontSize: 13,
    color: '#DC2626',
    fontWeight: '600',
    flex: 1,
  },
  retryBtn: {
    marginTop: 4,
  },
  retryBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#DC2626',
    textDecorationLine: 'underline',
  },

  /* SUBMIT BUTTON */
  submitButton: {
    backgroundColor: '#1E4D2B',
    borderRadius: 16,
    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#1E4D2B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 4,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  /* SUCCESS MODAL */
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successModalCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  successIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#1E4D2B',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  successModalTitle: {
    fontSize: 21,
    fontWeight: '800',
    color: '#163523',
    marginBottom: 8,
  },
  successModalSub: {
    fontSize: 13,
    color: '#556E60',
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 16,
  },
  successSummaryBox: {
    width: '100%',
    backgroundColor: '#F5FAF7',
    borderWidth: 1,
    borderColor: '#E1ECE5',
    borderRadius: 14,
    padding: 12,
    gap: 6,
    marginBottom: 20,
  },
  summaryRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryLabel: {
    fontSize: 12,
    color: '#637A6D',
    fontWeight: '600',
  },
  summaryValue: {
    fontSize: 12.5,
    color: '#163523',
    fontWeight: '700',
    maxWidth: '60%',
  },
  successDoneButton: {
    backgroundColor: '#1E4D2B',
    width: '100%',
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successDoneButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  /* PHOTOS & FILE ATTACHMENTS STYLES */
  attachCardHeaderTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  attachCountBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  attachCountText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#15803D',
  },
  attachActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
    marginBottom: 4,
  },
  attachActionBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 14,
    borderWidth: 1.2,
    backgroundColor: '#FFFFFF',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  attachActionBtnDisabled: {
    opacity: 0.45,
  },
  attachActionBtnCamera: {
    borderColor: '#C6EAD3',
    backgroundColor: '#F6FCF8',
  },
  attachActionBtnGallery: {
    borderColor: '#BAE6FD',
    backgroundColor: '#F0F9FF',
  },
  attachActionBtnFiles: {
    borderColor: '#FDE68A',
    backgroundColor: '#FFFDF5',
  },
  attachActionIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  attachActionBtnText: {
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 1,
  },
  attachActionBtnSub: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '600',
  },
  attachmentLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
    marginTop: 4,
  },
  attachmentLoadingText: {
    fontSize: 12,
    color: '#1E4D2B',
    fontWeight: '600',
  },
  attachmentListWrapper: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#ECF4EF',
  },
  attachListHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  attachmentListTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#163523',
  },
  attachTapHint: {
    fontSize: 10.5,
    color: '#658172',
    fontStyle: 'italic',
  },
  attachmentListGrid: {
    gap: 8,
  },
  attachImageItemCard: {
    position: 'relative',
    marginRight: 8,
  },
  attachImageItemInner: {
    position: 'relative',
    width: 90,
    height: 90,
  },
  attachImageThumbWrapper: {
    width: 90,
    height: 90,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F1F5F9',
    borderWidth: 1.2,
    borderColor: '#CBD5E1',
    position: 'relative',
  },
  attachImageThumb: {
    width: '100%',
    height: '100%',
  },
  attachImageBadge: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  attachImageBadgeText: {
    fontSize: 9,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  attachRemoveBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#DC2626',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    zIndex: 10,
  },
  attachDocItemCard: {
    backgroundColor: '#FAFDFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D4E2DA',
    padding: 10,
  },
  attachDocCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  attachDocIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachDocMeta: {
    flex: 1,
  },
  attachDocName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#163523',
    marginBottom: 2,
  },
  attachDocSize: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '500',
  },
  attachDocRemoveBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* FULLSCREEN IMAGE PREVIEW */
  imagePreviewModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  imagePreviewCloseBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  imagePreviewFull: {
    width: '100%',
    height: '80%',
  },
});
