import { Platform, StyleSheet } from 'react-native';
import { useMemo } from 'react';
import { useTheme } from '../../theme/ThemeContext';

export default function useRequestFormStyles() {
  const { colors } = useTheme();
  return useMemo(
    () =>
      StyleSheet.create({
        flex: {
          flex: 1,
        },
        scrollContent: {
          paddingVertical: 18,
          paddingHorizontal: 16,
          paddingBottom: 50,
        },
        formContainer: {
          width: '100%',
          maxWidth: 680,
          alignSelf: 'center',
          gap: 16,
        },
        generalErrorBanner: {
          flexDirection: 'row',
          alignItems: 'center',
          gap: 8,
          backgroundColor: colors.dangerSurface,
          borderWidth: 1,
          borderColor: colors.dangerBorder,
          borderRadius: 12,
          padding: 12,
        },
        generalErrorText: {
          fontSize: 14,
          color: colors.danger,
          fontWeight: '600',
          flex: 1,
        },
        card: {
          backgroundColor: colors.card,
          borderRadius: 18,
          borderWidth: 1,
          borderColor: colors.border,
          padding: 16,
          gap: 14,
          shadowColor: colors.shadow,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0,
          shadowRadius: 6,
          elevation: 0,
        },
        cardHeaderRow: {
          flexDirection: 'row',
          alignItems: 'center',
          gap: 8,
          paddingBottom: 10,
          borderBottomWidth: 0,
          borderBottomColor: colors.border,
        },
        cardTitle: {
          fontSize: 15,
          fontWeight: '700',
          color: colors.text,
          letterSpacing: -0.2,
        },
        cardSubText: {
          fontSize: 12,
          color: colors.textMuted,
          lineHeight: 16,
          marginTop: -6,
        },
        fieldBlock: {
          gap: 6,
        },
        fieldLabelRow: {
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
        },
        fieldLabel: {
          fontSize: 13,
          fontWeight: '700',
          color: colors.text,
        },
        fieldLabelError: {
          color: colors.danger,
          fontWeight: '700',
        },
        counterText: {
          fontSize: 11,
          color: colors.muted,
          fontWeight: '600',
        },
        requiredBadge: {
          fontSize: 11,
          fontWeight: '700',
          color: colors.danger,
          backgroundColor: colors.dangerSurface,
          paddingHorizontal: 6,
          paddingVertical: 2,
          borderRadius: 6,
        },
        inputWithIcon: {
          flexDirection: 'row',
          alignItems: 'center',
          backgroundColor: colors.input,
          borderWidth: 1,
          borderColor: colors.border,
          borderRadius: 12,
          paddingHorizontal: 10,
          minHeight: 48,
        },
        inputErrorBorder: {
          borderColor: colors.danger,
          borderWidth: 1.6,
          backgroundColor: colors.dangerSurface,
        },
        currencySymbolBadgeError: {
          backgroundColor: colors.dangerSurface,
          borderRightColor: colors.danger,
        },
        fieldErrorText: {
          fontSize: 12,
          fontWeight: '600',
          color: colors.danger,
          marginTop: 2,
        },
        leadingIcon: {
          marginRight: 6,
        },
        textInputInner: {
          flex: 1,
          fontSize: 14,
          color: colors.text,
          fontWeight: '500',
          paddingVertical: 12,
          paddingHorizontal: 0,
          minWidth: 0,
        },
        textareaWrapper: {
          backgroundColor: colors.input,
          borderWidth: 1,
          borderColor: colors.border,
          borderRadius: 12,
          padding: 12,
          minHeight: 84,
        },
        textareaInput: {
          fontSize: 14,
          color: colors.text,
          lineHeight: 18,
        },
        pickerTrailingButton: {
          paddingLeft: 6,
          paddingRight: 2,
          height: '100%',
          alignItems: 'center',
          justifyContent: 'center',
        },
        categoryGrid: {
          flexDirection: 'row',
          flexWrap: 'wrap',
          gap: 8,
        },
        categoryBtn: {
          flexDirection: 'row',
          alignItems: 'center',
          gap: 6,
          paddingHorizontal: 12,
          paddingVertical: 8,
          borderRadius: 12,
          borderWidth: 1,
        },
        categoryBtnActive: {
          backgroundColor: colors.primary,
          borderColor: colors.link,
          shadowColor: colors.link,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0,
          shadowRadius: 4,
          elevation: 0,
        },
        categoryBtnInactive: {
          backgroundColor: colors.surface,
          borderColor: colors.border,
        },
        categoryBtnText: {
          fontSize: 14,
          fontWeight: '600',
        },
        categoryBtnTextActive: {
          color: colors.onPrimary,
          fontWeight: '700',
        },
        categoryBtnTextInactive: {
          color: colors.text,
        },
        currencyInputRow: {
          flexDirection: 'row',
          alignItems: 'center',
          backgroundColor: colors.input,
          borderWidth: 1,
          borderColor: colors.border,
          borderRadius: 12,
          overflow: 'hidden',
          height: 50,
        },
        currencySymbolBadge: {
          width: 48,
          height: '100%',
          backgroundColor: colors.surfaceAlt,
          alignItems: 'center',
          justifyContent: 'center',
          borderRightWidth: 1,
          borderRightColor: colors.border,
        },
        currencySymbolText: {
          fontSize: 18,
          fontWeight: '700',
          color: colors.link,
        },
        currencyInput: {
          flex: 1,
          paddingHorizontal: 14,
          fontSize: 17,
          fontWeight: '700',
          color: colors.text,
        },
        presetsRow: {
          flexDirection: 'row',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: 6,
        },
        presetsLabel: {
          fontSize: 12,
          fontWeight: '600',
          color: colors.textMuted,
          marginRight: 2,
        },
        presetPill: {
          backgroundColor: colors.surfaceAlt,
          borderWidth: 1,
          borderColor: colors.border,
          paddingHorizontal: 10,
          paddingVertical: 5,
          borderRadius: 8,
        },
        presetPillActive: {
          backgroundColor: colors.primary,
          borderColor: colors.link,
        },
        presetPillText: {
          fontSize: 12,
          fontWeight: '700',
          color: colors.link,
        },
        presetPillTextActive: {
          color: colors.onPrimary,
        },
        dateTimeRow: {
          flexDirection: 'row',
          gap: 12,
        },
        dateTimeCol: {
          flex: 1,
          gap: 6,
        },
        dateTimeInputWrapper: {
          flexDirection: 'row',
          alignItems: 'center',
          backgroundColor: colors.input,
          borderWidth: 1,
          borderColor: colors.border,
          borderRadius: 12,
          paddingHorizontal: 10,
          height: 48,
        },
        deadlineContainerPill: {
          flexDirection: 'row',
          alignItems: 'center',
          gap: 6,
          backgroundColor: colors.surfaceAlt,
          paddingHorizontal: 10,
          paddingVertical: 6,
          borderRadius: 8,
          alignSelf: 'flex-start',
        },
        deadlinePillText: {
          fontSize: 12,
          fontWeight: '700',
          color: colors.link,
        },
        errorCard: {
          flexDirection: 'row',
          alignItems: 'center',
          gap: 10,
          backgroundColor: colors.dangerSurface,
          borderWidth: 1,
          borderColor: colors.dangerBorder,
          borderRadius: 14,
          padding: 12,
        },
        errorCardText: {
          fontSize: 13,
          color: colors.danger,
          fontWeight: '600',
          flex: 1,
        },
        retryBtn: {
          marginTop: 4,
        },
        retryBtnText: {
          fontSize: 12,
          fontWeight: '700',
          color: colors.danger,
          textDecorationLine: 'underline',
        },
        submitButton: {
          backgroundColor: colors.primary,
          borderRadius: 16,
          height: 54,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 8,
          shadowColor: colors.link,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.25,
          shadowRadius: 8,
          elevation: 4,
          marginTop: 4,
        },
        submitButtonDisabled: {
          opacity: 0.6,
        },
        submitButtonText: {
          fontSize: 16,
          fontWeight: '700',
          color: colors.onPrimary,
          letterSpacing: 0.2,
        },
        modalBackdrop: {
          flex: 1,
          backgroundColor: 'rgba(0, 0, 0, 0.55)',
          justifyContent: 'center',
          alignItems: 'center',
          paddingHorizontal: 24,
        },
        successModalCard: {
          width: '100%',
          maxWidth: 400,
          backgroundColor: colors.card,
          borderRadius: 24,
          padding: 24,
          alignItems: 'center',
          shadowColor: colors.shadow,
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.15,
          shadowRadius: 20,
          elevation: 10,
        },
        successIconCircle: {
          width: 72,
          height: 72,
          borderRadius: 36,
          backgroundColor: colors.primary,
          alignItems: 'center',
          justifyContent: 'center',
          marginBottom: 16,
        },
        successModalTitle: {
          fontSize: 21,
          fontWeight: '700',
          color: colors.text,
          marginBottom: 8,
        },
        successModalSub: {
          fontSize: 13,
          color: colors.textMuted,
          textAlign: 'center',
          lineHeight: 19,
          marginBottom: 16,
        },
        successSummaryBox: {
          width: '100%',
          backgroundColor: colors.surface,
          borderWidth: 1,
          borderColor: colors.border,
          borderRadius: 14,
          padding: 12,
          gap: 6,
          marginBottom: 20,
        },
        summaryRowItem: {
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
        },
        summaryLabel: {
          fontSize: 12,
          color: colors.textMuted,
          fontWeight: '600',
        },
        summaryValue: {
          fontSize: 14,
          color: colors.text,
          fontWeight: '700',
          maxWidth: '60%',
        },
        successDoneButton: {
          backgroundColor: colors.primary,
          width: '100%',
          height: 48,
          borderRadius: 14,
          alignItems: 'center',
          justifyContent: 'center',
        },
        successDoneButtonText: {
          fontSize: 15,
          fontWeight: '700',
          color: colors.onPrimary,
        },
      }),
    [colors],
  );
}
